# Generated by Django 5.1 on 2024-08-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alter_habit_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="pleasant_habit",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте, если привычка приятная.",
                verbose_name="Приятная привычка",
            ),
        ),
    ]
